
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 24 20:58:00 CEST 2017
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SEMICOLON = 17;
  public static final int ELSE = 4;
  public static final int STRUCT = 12;
  public static final int OR = 25;
  public static final int INT = 7;
  public static final int EQUAL = 23;
  public static final int CONSTANT = 2;
  public static final int POINT = 22;
  public static final int RETURN = 11;
  public static final int PRINTI = 10;
  public static final int IF = 6;
  public static final int TCHAIN = 27;
  public static final int ASSIGMENT = 16;
  public static final int OBRACKET = 18;
  public static final int ID = 14;
  public static final int CBRACKET = 19;
  public static final int PRINTC = 9;
  public static final int NUM = 15;
  public static final int COMMA = 26;
  public static final int EOF = 0;
  public static final int MORE = 24;
  public static final int MAIN = 8;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int OBRACE = 20;
  public static final int CBRACE = 21;
  public static final int FOR = 5;
  public static final int VOID = 13;
}

